export const GAMES_CLEANUP = 'GAMES_CLEANUP';
export const GAMES_FETCH = 'GAMES_FETCH';
export const GAMES_FETCH_SUCCESS = 'GAMES_FETCH_SUCCESS';
export const GAMES_FETCH_FAILURE = 'GAMES_FETCH_FAILURE';
export const GENRES_FETCH_SUCCESS = 'GENRES_FETCH_SUCCESS';
export const GENRES_FETCH_FAILURE = 'GENRES_FETCH_FAILURE';
