export const GAME_CLEANUP = 'GAME_CLEANUP';
export const GAME_FETCH = 'GAME_FETCH';
export const GAME_FETCH_SUCCESS = 'GAME_FETCH_SUCCESS';
export const GAME_FETCH_FAILURE = 'GAME_FETCH_FAILURE';
export const GAME_UPDATE = 'GAME_UPDATE';
export const GAME_UPDATE_SUCCESS = 'GAME_UPDATE_SUCCESS';
export const GAME_UPDATE_FAILURE = 'GAME_UPDATE_FAILURE';
